list: $/chiragpatel/bootstrapcollapse/models/collapse/columns.yaml
modelClass: ChiragPatel\BootstrapCollapse\Models\Collapse
title: Bootstrap Collapse
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'chiragpatel/bootstrapcollapse/collapses/update/:id'
